version: '3.1'

services:
  python:
    build: ./src
    depends_on:
      - mongo
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: todo
    ports:
      - 27017:27017
